### ISSUE TITLE
Can't add axios request/response interceptors

### ISSUE THREAD

**Issue by jonathan-chancetop** [neowu/core-fe-project#25]
Hello, I see now the lib use created axios client to do the network request instead of using the axios itself, and the client is not exported, that makes us nowhere to add customize interceptors, is there any way to do that, or should we export the axios client.

**Comment by neowu** [comment]
Hi, Jonathan
We don't have any use case to add network interceptor in core-fe, generally it's only used to talk to core-ng backend services, and it already has everything we need, such as tracking, logging, error handling

What's your use case of adding network interceptor? and I guess if you have more tailored requirement, you may consider to fork core-fe, since it's relative small, and not hard to maintain

thx

**Comment by dionshihk** [comment]
We do not export the wrapped `axios` client, but you can customize the axios config while using `ajax()` function by passing the 5th argument `extraConfig`

In the `extraConfig`, you can customize request/response interceptors, just for this AJAX call.

```TypeScript
export async function ajax<Request, Response, Path extends string>(method: Method, path: Path, pathParams: PathParams<Path>, request: Request, extraConfig?: Partial<AxiosRequestConfig> = {}): Promise<Response>
```

To make your interceptor global, you can write your version's `ajax()` in your project, and unify all AJAX calls to your specific version.

Thanks.

**Comment by jonathan-chancetop** [comment]
Ok, that makes sense, thanks.
