### ISSUE TITLE
Plan to upgrade react-router?

### ISSUE THREAD

**Issue by jonathan-chancetop** [neowu/core-fe-project#30]
Hello, is there any plan to upgrade react-router? I know that connected-react-router is not maintained now, maybe can switch to an alternative lib like https://github.com/salvoravida/redux-first-history?

**Comment by dionshihk** [comment]
Thanks for your suggestion.

I tried to upgrade before last year and there are some runtime issues while rendering the root route component. So I did not replace the `connected-react-router` library.

I will try the latest version of `redux-first-history` in the next version to see if it works well.

**Comment by dionshihk** [comment]
Hi @jonathan-chancetop,

We've released core-fe `13.7.0` today, replacing `connected-react-router` to latest `redux-first-history` library.

But we have not upgraded `history` and `react-router` library yet, because of breaking change and some open issues, which affects our existing system.

We will keep following the issues to see if we can upgrade the whole router system in the near future. 
Thank you.
